//! Cross-check Eip712AgentSigner against hyperliquid-python-sdk known vectors.
//!
//! Fixture is generated by the upstream `scripts/gen_signing_vectors.py`; do
//! not edit `tests/fixtures/signing/known_vectors.json` by hand.
//!
//! Copied verbatim from `diff-old-new/executor/crates/executor-hl/tests/`;
//! only the crate import paths changed. Passing the original 10/10 is the
//! proof that the msgpack field order and EIP-712 domain survived the port.
//!
//! Issue #2 (Task 5) added 7 MORE vectors covering `expiresAfter` (generated
//! the same way, via a local hyperliquid-python-sdk venv — see
//! `.superpowers/sdd/issues-1-10-hardening/task-5-report.md` for the
//! generator script). The original 10 vectors are byte-for-byte untouched;
//! the new ones are appended after them. 10 + 7 = 17 total.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use hype_trigger_twap::signer::{Eip712AgentSigner, Signer};
use hype_trigger_twap::types::Address as CoreAddress;
use secrecy::SecretString;
use serde::Deserialize;
use std::path::PathBuf;

/// Normalize a `0x`-prefixed hex string to lowercase 64-hex (32-byte) form.
/// HL python-sdk emits unpadded hex via `eth_utils.to_hex(int)`, which strips
/// leading zero nibbles when the high nibble of the integer is 0. The Rust
/// `Eip712AgentSigner` always emits zero-padded 64-hex via `format!("{:064x}")`.
/// Both representations encode the SAME integer value — this normalizer makes
/// the byte-identical comparison robust against that representation difference.
fn norm_hex32(s: &str) -> String {
    let body = s.strip_prefix("0x").unwrap_or(s).to_lowercase();
    if body.len() > 64 {
        panic!("hex string longer than 64 chars: {s}");
    }
    format!("0x{:0>64}", body)
}

#[derive(Debug, Deserialize)]
struct Vector {
    name: String,
    action: serde_json::Value,
    nonce: u64,
    vault_address: Option<String>,
    expires_after: Option<u64>,
    is_mainnet: bool,
    expected_r: String,
    expected_s: String,
    expected_v: u8,
    expected_address: String,
}

const TEST_PK: &str = "0x0123456789012345678901234567890123456789012345678901234567890123";

fn vectors() -> Vec<Vector> {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/signing/known_vectors.json");
    let s = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {p:?}: {e}"));
    serde_json::from_str(&s).unwrap_or_else(|e| panic!("parse fixture: {e}"))
}

#[test]
fn fixture_loads_with_17_vectors() {
    let v = vectors();
    assert_eq!(
        v.len(),
        17,
        "fixture should have 17 vectors (10 original + 7 expiresAfter, Issue #2)"
    );
}

#[tokio::test]
async fn signer_address_matches_test_pk() {
    let s = Eip712AgentSigner::from_secret(SecretString::new(TEST_PK.into()), true).unwrap();
    let addr = s.address().as_str().to_lowercase();
    // 0x + 40 hex
    assert!(
        addr.starts_with("0x") && addr.len() == 42,
        "addr shape: {addr}"
    );
    // Must equal what eth_account derives from the same PK; pulled from the fixture.
    let v = vectors();
    let expected = &v[0].expected_address;
    assert_eq!(addr, *expected, "PK -> address mismatch");
}

#[tokio::test]
async fn cross_check_all_known_vectors() {
    let mut failed: Vec<String> = Vec::new();
    let mut checked = 0usize;
    for v in vectors() {
        checked += 1;
        // Parse vault if present (crate::types::Address is a String wrapper).
        let vault: Option<CoreAddress> = v.vault_address.as_deref().map(CoreAddress::new);

        let signer =
            Eip712AgentSigner::from_secret(SecretString::new(TEST_PK.into()), v.is_mainnet)
                .unwrap();

        // Address sanity check
        assert_eq!(
            signer.address().as_str().to_lowercase(),
            v.expected_address,
            "address mismatch for {}",
            v.name
        );

        let sig = match signer
            .sign_l1(&v.action, v.nonce, vault.as_ref(), v.expires_after)
            .await
        {
            Ok(s) => s,
            Err(e) => {
                failed.push(format!("{}: sign_l1 errored: {e}", v.name));
                continue;
            }
        };

        let got_r = norm_hex32(&sig.r);
        let exp_r = norm_hex32(&v.expected_r);
        if got_r != exp_r {
            failed.push(format!(
                "{}: r mismatch\n  got:      {}\n  expected: {}",
                v.name, got_r, exp_r
            ));
        }
        let got_s = norm_hex32(&sig.s);
        let exp_s = norm_hex32(&v.expected_s);
        if got_s != exp_s {
            failed.push(format!(
                "{}: s mismatch\n  got:      {}\n  expected: {}",
                v.name, got_s, exp_s
            ));
        }
        if sig.v != v.expected_v {
            failed.push(format!(
                "{}: v mismatch\n  got:      {}\n  expected: {}",
                v.name, sig.v, v.expected_v
            ));
        }
    }
    eprintln!("\n=== cross-check summary ===");
    eprintln!("vectors checked: {checked} (all)");
    assert_eq!(checked, 17, "expected to check all 17 vectors");
    if !failed.is_empty() {
        panic!("\ncross-check failures:\n{}\n", failed.join("\n\n"));
    }
}
